server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # Se não achar o arquivo, redireciona para o index.html (Magia do Angular)
        try_files $uri $uri/ /index.html;
    }
}