server {
    listen 80;
    
    location /contador-calorias {
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # Se não achar o arquivo, redireciona para o index.html (Magia do Angular)
        try_files $uri $uri/ /contador-calorias/index.html;
    }

    location = / {
        return 301 /contador-calorias/;
    }
}