services:
  # Caddy (Proxy Reverso com HTTPS automático)
  caddy:
    image: caddy:2-alpine
    container_name: contador-calorias-caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

  # Banco de Dados
  db:
    image: postgres:16-alpine
    container_name: contador-calorias-db
    restart: always
    environment:
      POSTGRES_DB: CalculadoraCaloriasDb
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: Senha123@
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  # Interface visual para o Banco de Dados
  pgadmin:
    image: dpage/pgadmin4
    container_name: contador-calorias-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: contador-calorias-api
    restart: always
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=CalculadoraCaloriasDb;Username=usuario;Password=Senha123@;
      - Gemini__ApiKey=${GEMINI_API_KEY}
    volumes:
      - ./backend/CalculadoraCalorias.Api/wwwroot/uploads:/app/wwwroot/uploads

  # Frontend  
  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      container_name: contador-calorias-front
      restart: always
      depends_on:
        - backend

volumes:
  db-data:
  caddy_data:
  caddy_config:
