// <auto-generated />
using System;
using CalculadoraCalorias.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CalculadoraCalorias.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314004334_AtualizacaoTabelaAtividadeFisica")]
    partial class AtualizacaoTabelaAtividadeFisica
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CalculadoraCalorias.Core.Domain.Entities.AtividadeFisica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CaloriasEstimadas")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("DataExercicio")
                        .HasColumnType("date");

                    b.Property<decimal?>("PesoSnapshot")
                        .HasColumnType("numeric");

                    b.Property<TimeSpan>("TempoExercicio")
                        .HasColumnType("interval");

                    b.Property<int>("TipoAtividadeId")
                        .HasColumnType("integer");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<double?>("VelocidadeMedia")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AtividadeFisica");
                });

            modelBuilder.Entity("CalculadoraCalorias.Core.Domain.Entities.PerfilBiometrico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AlturaCm")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Genero")
                        .HasColumnType("integer");

                    b.Property<int>("NivelAtividade")
                        .HasColumnType("integer");

                    b.Property<int>("Objetivo")
                        .HasColumnType("integer");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("PerfilBiometrico");
                });

            modelBuilder.Entity("CalculadoraCalorias.Core.Domain.Entities.Refeicao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("Acucares")
                        .HasColumnType("double precision");

                    b.Property<string>("Alimento")
                        .HasColumnType("text");

                    b.Property<string>("Apelido")
                        .HasColumnType("text");

                    b.Property<double?>("Calorias")
                        .HasColumnType("double precision");

                    b.Property<double?>("Carboidratos")
                        .HasColumnType("double precision");

                    b.Property<long?>("CodigoRefeicaoModelo")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<double?>("Fibras")
                        .HasColumnType("double precision");

                    b.Property<double?>("Gorduras")
                        .HasColumnType("double precision");

                    b.Property<Guid>("GuidArquivo")
                        .HasColumnType("uuid");

                    b.Property<int>("Peso")
                        .HasColumnType("integer");

                    b.Property<double?>("Proteinas")
                        .HasColumnType("double precision");

                    b.Property<long?>("RefeicaoModeloId")
                        .HasColumnType("bigint");

                    b.Property<int>("StatusProcessamento")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("UtilizadoRefeicaoModelo")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("RefeicaoModeloId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Refeicao");
                });

            modelBuilder.Entity("CalculadoraCalorias.Core.Domain.Entities.RegistroFisico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ImcCalculado")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MetaCaloricaDiaria")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PesoKg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TaxaMetabolicaBasal")
                        .HasColumnType("numeric");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RegistroFisico");
                });

            modelBuilder.Entity("CalculadoraCalorias.Core.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CalculadoraCalorias.Core.Domain.Entities.AtividadeFisica", b =>
                {
                    b.HasOne("CalculadoraCalorias.Core.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CalculadoraCalorias.Core.Domain.Entities.PerfilBiometrico", b =>
                {
                    b.HasOne("CalculadoraCalorias.Core.Domain.Entities.Usuario", "Usuario")
                        .WithOne("PerfilBiometrico")
                        .HasForeignKey("CalculadoraCalorias.Core.Domain.Entities.PerfilBiometrico", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CalculadoraCalorias.Core.Domain.Entities.Refeicao", b =>
                {
                    b.HasOne("CalculadoraCalorias.Core.Domain.Entities.Refeicao", "RefeicaoModelo")
                        .WithMany()
                        .HasForeignKey("RefeicaoModeloId");

                    b.HasOne("CalculadoraCalorias.Core.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RefeicaoModelo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CalculadoraCalorias.Core.Domain.Entities.RegistroFisico", b =>
                {
                    b.HasOne("CalculadoraCalorias.Core.Domain.Entities.Usuario", "Usuario")
                        .WithMany("RegistroFisico")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CalculadoraCalorias.Core.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("PerfilBiometrico")
                        .IsRequired();

                    b.Navigation("RegistroFisico");
                });
#pragma warning restore 612, 618
        }
    }
}
