// <auto-generated />
using System;
using CalculadoraCalorias.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CalculadoraCalorias.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260203020053_AtividadeFisicaMigration")]
    partial class AtividadeFisicaMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CalculadoraCalorias.Core.Domain.Entities.AtividadeFisica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CaloriasCalculadas")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DataExercicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("integer");

                    b.Property<decimal>("PesoSnapshot")
                        .HasColumnType("numeric");

                    b.Property<int>("TipoAtividadeId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<long?>("UsuarioId1")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId1");

                    b.ToTable("AtividadeFisica");
                });

            modelBuilder.Entity("CalculadoraCalorias.Core.Domain.Entities.PerfilBiometrico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AlturaCm")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Genero")
                        .HasColumnType("integer");

                    b.Property<int>("NivelAtividade")
                        .HasColumnType("integer");

                    b.Property<int>("Objetivo")
                        .HasColumnType("integer");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioId1")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.HasIndex("UsuarioId1")
                        .IsUnique();

                    b.ToTable("PerfilBiometrico");
                });

            modelBuilder.Entity("CalculadoraCalorias.Core.Domain.Entities.RegistroFisico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ImcCalculado")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MetaCaloricaDiaria")
                        .HasColumnType("numeric");

                    b.Property<long>("PerfilBiometricoId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PesoKg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TaxaMetabolicaBasal")
                        .HasColumnType("numeric");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UsuarioId1")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PerfilBiometricoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId1")
                        .IsUnique();

                    b.ToTable("RegistroFisico");
                });

            modelBuilder.Entity("CalculadoraCalorias.Core.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CalculadoraCalorias.Core.Domain.Entities.AtividadeFisica", b =>
                {
                    b.HasOne("CalculadoraCalorias.Core.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId1");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CalculadoraCalorias.Core.Domain.Entities.PerfilBiometrico", b =>
                {
                    b.HasOne("CalculadoraCalorias.Core.Domain.Entities.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("CalculadoraCalorias.Core.Domain.Entities.PerfilBiometrico", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalculadoraCalorias.Core.Domain.Entities.Usuario", null)
                        .WithOne("PerfilBiometrico")
                        .HasForeignKey("CalculadoraCalorias.Core.Domain.Entities.PerfilBiometrico", "UsuarioId1");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CalculadoraCalorias.Core.Domain.Entities.RegistroFisico", b =>
                {
                    b.HasOne("CalculadoraCalorias.Core.Domain.Entities.PerfilBiometrico", "PerfilBiometrico")
                        .WithMany()
                        .HasForeignKey("PerfilBiometricoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalculadoraCalorias.Core.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalculadoraCalorias.Core.Domain.Entities.Usuario", null)
                        .WithOne("RegistroFisico")
                        .HasForeignKey("CalculadoraCalorias.Core.Domain.Entities.RegistroFisico", "UsuarioId1");

                    b.Navigation("PerfilBiometrico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CalculadoraCalorias.Core.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("PerfilBiometrico")
                        .IsRequired();

                    b.Navigation("RegistroFisico")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
